/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.vendorrole;

import business.Business;
import business.enterprise.Enterprise;
import business.organization.message.Message;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raseswaridas
 */
public class VendorRoleWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Business business;
    private ArrayList<Message> complaintsList;

    /**
     * Creates new form VendorRoleWorkAreaJPanel
     */
    public VendorRoleWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
        
        complaintsList = new ArrayList<Message>();
        
        int openMessages = 0;
        int totalMessages = 0;
        for(Message message:business.getMessageDirectory().getMessageList()){
            if(message.getType() == Message.messageType.WorkOrder){
                if(message.getReceiver().getEmail().equals(userAccount.getEmail())){
                    complaintsList.add(message);
                    totalMessages++;
                    if((message.getStatus().toString().equals(Message.statusType.Open.toString())) || (message.getStatus().toString().equals(Message.statusType.InProgressWithMaintenance.toString()))){
                        openMessages++;
                    }
                }
            }
        }
        
        labelNewComplaintCount.setText(String.valueOf(openMessages));
        labelTotalComplaintCount.setText(String.valueOf(totalMessages));
        
        populateTable();
    }
    
    public void refreshTable(){
        
        complaintsList = new ArrayList<Message>();
        int openMessages = 0;
        int totalMessages = 0;
        for(Message message:business.getMessageDirectory().getMessageList()){
            if(message.getType() == Message.messageType.WorkOrder){
                if(message.getReceiver().getEmail().equals(userAccount.getEmail())){
                    complaintsList.add(message);
                    totalMessages++;
                    if((message.getStatus().toString().equals(Message.statusType.Open.toString())) || (message.getStatus().toString().equals(Message.statusType.InProgressWithMaintenance.toString()))){
                        openMessages++;
                    }
                }
            }
        }
        
        labelNewComplaintCount.setText(String.valueOf(openMessages));
        labelTotalComplaintCount.setText(String.valueOf(totalMessages));
        
        populateTable();
        
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tableVendorComplaint.getModel();
        dtm.setRowCount(0);
        
        for(Message message: complaintsList){
            Object row[] = new Object[5];
            row[0] = message;
            row[1] = message.getRequestDate();
            row[2] = message.getSender();
            row[3] = message.getSubject();
            row[4] = message.getStatus();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableVendorComplaint = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnViewComplaint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelNewComplaintCount = new javax.swing.JLabel();
        labelTotalComplaintCount = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(new java.awt.Color(255, 204, 0));

        tableVendorComplaint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Complaint ID", "Date", "Sender", "Subject", "Status"
            }
        ));
        jScrollPane2.setViewportView(tableVendorComplaint);

        jLabel1.setFont(new java.awt.Font("Yuppy SC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vendor Dashboard");

        btnViewComplaint.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnViewComplaint.setForeground(new java.awt.Color(255, 153, 0));
        btnViewComplaint.setText("View Complaint");
        btnViewComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewComplaintActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("New Complaints:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Total Complaints:");

        labelNewComplaintCount.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelNewComplaintCount.setForeground(new java.awt.Color(255, 204, 0));
        labelNewComplaintCount.setText("<Number>");

        labelTotalComplaintCount.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelTotalComplaintCount.setForeground(new java.awt.Color(255, 204, 0));
        labelTotalComplaintCount.setText("<Number>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnViewComplaint)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNewComplaintCount)
                                            .addComponent(labelTotalComplaintCount))
                                        .addGap(499, 499, 499)))))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNewComplaintCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelTotalComplaintCount))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(btnViewComplaint)
                .addGap(111, 111, 111))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewComplaintActionPerformed
        // TODO add your handling code here:
        int row = tableVendorComplaint.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Message message = (Message) tableVendorComplaint.getValueAt(row, 0);
        ViewComplaintJPanel viewComplaintJPanel = new ViewComplaintJPanel(userProcessContainer, business, message);
        userProcessContainer.add("ViewComplaintJPanel", viewComplaintJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewComplaintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewComplaint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNewComplaintCount;
    private javax.swing.JLabel labelTotalComplaintCount;
    private javax.swing.JTable tableVendorComplaint;
    // End of variables declaration//GEN-END:variables
}
