/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.adminrole;

import business.Business;
import business.enterprise.Enterprise;
import business.useraccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author Skull
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Business business;
    private Enterprise enterprise;
    
    /**
     * Creates new form AdminRoleWorkAreaJPanel
     */
    public AdminRoleWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageClasses = new javax.swing.JButton();
        btnManageTrainers = new javax.swing.JButton();
        btnManageCustomers = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("My Work Area - Admin Role");

        btnManageClasses.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageClasses.setForeground(new java.awt.Color(255, 204, 0));
        btnManageClasses.setText("Manage Classes >>");
        btnManageClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageClassesActionPerformed(evt);
            }
        });

        btnManageTrainers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageTrainers.setForeground(new java.awt.Color(255, 204, 0));
        btnManageTrainers.setText("Manage Employees >>");
        btnManageTrainers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTrainersActionPerformed(evt);
            }
        });

        btnManageCustomers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageCustomers.setForeground(new java.awt.Color(255, 204, 0));
        btnManageCustomers.setText("Manage Customers >>");
        btnManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(554, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(btnManageTrainers, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(554, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(141, 141, 141)
                .addComponent(btnManageCustomers)
                .addGap(18, 18, 18)
                .addComponent(btnManageClasses)
                .addContainerGap(336, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(btnManageTrainers)
                    .addContainerGap(434, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageClassesActionPerformed
        //        ManageSuppliers ms = new ManageSuppliers(userProcessContainer, supplierDirectory);
        //        userProcessContainer.add("ManageSupplierAdministrative", ms);
        //        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageClassesActionPerformed

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnManageTrainersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTrainersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageTrainersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageClasses;
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnManageTrainers;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
