/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customerrole;

import business.Business;
import business.organization.accounting.Accounting;
import business.organization.accounting.membership.Membership;
import business.organization.accounting.membership.MembershipDirectory;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author soumiyaroy
 */
public class MembershipJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Accounting accounting;
    private Business business;
    private ArrayList<Membership> membershipList;

    /**
     * Creates new form MembershipJPanel
     */
    public MembershipJPanel(JPanel userProcessContainer, UserAccount userAccount, Accounting accounting, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.accounting = accounting;
        this.business = business;
        
        populateMembershipData();
        
        if(userAccount.getCustomer().getMembership().getHasPersonalTraining())
            radioBtnYes.setSelected(true);
        else
            radioBtnNo.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroupMembership = new javax.swing.ButtonGroup();
        buttonGroupHasPersonalTraining = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioBtnPlan1 = new javax.swing.JRadioButton();
        radioBtnPlan2 = new javax.swing.JRadioButton();
        radioBtnPlan3 = new javax.swing.JRadioButton();
        radioBtnPlan4 = new javax.swing.JRadioButton();
        radioBtnPlan5 = new javax.swing.JRadioButton();
        radioBtnPlan6 = new javax.swing.JRadioButton();
        lblPrice2 = new javax.swing.JLabel();
        lblPrice4 = new javax.swing.JLabel();
        lblPrice3 = new javax.swing.JLabel();
        lblPrice5 = new javax.swing.JLabel();
        lblPrice6 = new javax.swing.JLabel();
        lblPrice1 = new javax.swing.JLabel();
        btnDetails3 = new javax.swing.JButton();
        btnDetails1 = new javax.swing.JButton();
        btnDetails2 = new javax.swing.JButton();
        btnDetails4 = new javax.swing.JButton();
        btnDetails5 = new javax.swing.JButton();
        btnDetails6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        radioBtnYes = new javax.swing.JRadioButton();
        radioBtnNo = new javax.swing.JRadioButton();

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("$150");

        jCheckBox1.setText("jCheckBox1");

        setBackground(new java.awt.Color(102, 102, 255));

        jSeparator1.setForeground(new java.awt.Color(255, 204, 0));

        jSeparator2.setForeground(new java.awt.Color(255, 204, 0));

        btnRegister.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 204, 0));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 204, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yuppy SC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Membership");

        jLabel3.setFont(new java.awt.Font("YuGothic", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Choose Membership Plan:");

        buttonGroupMembership.add(radioBtnPlan1);
        radioBtnPlan1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        radioBtnPlan1.setForeground(new java.awt.Color(255, 204, 0));
        radioBtnPlan1.setText("Weekly Gym Membership- ");

        buttonGroupMembership.add(radioBtnPlan2);
        radioBtnPlan2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        radioBtnPlan2.setForeground(new java.awt.Color(255, 204, 0));
        radioBtnPlan2.setText("Monthly Gym Membership-");

        buttonGroupMembership.add(radioBtnPlan3);
        radioBtnPlan3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        radioBtnPlan3.setForeground(new java.awt.Color(255, 204, 0));
        radioBtnPlan3.setText("Yearly Gym Membership-");

        buttonGroupMembership.add(radioBtnPlan4);
        radioBtnPlan4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        radioBtnPlan4.setForeground(new java.awt.Color(255, 204, 0));
        radioBtnPlan4.setText("Weekly Gym Membership with Special Classes-");

        buttonGroupMembership.add(radioBtnPlan5);
        radioBtnPlan5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        radioBtnPlan5.setForeground(new java.awt.Color(255, 204, 0));
        radioBtnPlan5.setText("Monthly Gym Membership with Special Classes-");

        buttonGroupMembership.add(radioBtnPlan6);
        radioBtnPlan6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        radioBtnPlan6.setForeground(new java.awt.Color(255, 204, 0));
        radioBtnPlan6.setText("Yearly Gym Membership with Special Classes-");

        lblPrice2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblPrice2.setForeground(new java.awt.Color(255, 204, 0));
        lblPrice2.setText("$150");

        lblPrice4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblPrice4.setForeground(new java.awt.Color(255, 204, 0));
        lblPrice4.setText("$150");

        lblPrice3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblPrice3.setForeground(new java.awt.Color(255, 204, 0));
        lblPrice3.setText("$150");

        lblPrice5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblPrice5.setForeground(new java.awt.Color(255, 204, 0));
        lblPrice5.setText("$150");

        lblPrice6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblPrice6.setForeground(new java.awt.Color(255, 204, 0));
        lblPrice6.setText("$150");

        lblPrice1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblPrice1.setForeground(new java.awt.Color(255, 204, 0));
        lblPrice1.setText("$150");

        btnDetails3.setForeground(new java.awt.Color(102, 102, 255));
        btnDetails3.setText("Details");
        btnDetails3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetails3ActionPerformed(evt);
            }
        });

        btnDetails1.setForeground(new java.awt.Color(102, 102, 255));
        btnDetails1.setText("Details");
        btnDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetails1ActionPerformed(evt);
            }
        });

        btnDetails2.setForeground(new java.awt.Color(102, 102, 255));
        btnDetails2.setText("Details");
        btnDetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetails2ActionPerformed(evt);
            }
        });

        btnDetails4.setForeground(new java.awt.Color(102, 102, 255));
        btnDetails4.setText("Details");
        btnDetails4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetails4ActionPerformed(evt);
            }
        });

        btnDetails5.setForeground(new java.awt.Color(102, 102, 255));
        btnDetails5.setText("Details");
        btnDetails5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetails5ActionPerformed(evt);
            }
        });

        btnDetails6.setForeground(new java.awt.Color(102, 102, 255));
        btnDetails6.setText("Details");
        btnDetails6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetails6ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 0));
        jLabel11.setText("Need a trainer? ");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 0));
        jLabel18.setText("$50/day");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 0));
        jLabel20.setText("Total Amount:");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 204, 0));
        jLabel21.setText("$");

        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);

        buttonGroupHasPersonalTraining.add(radioBtnYes);
        radioBtnYes.setText("Yes");

        buttonGroupHasPersonalTraining.add(radioBtnNo);
        radioBtnNo.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegister))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radioBtnPlan3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnPlan2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnPlan1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrice3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrice2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(radioBtnPlan4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDetails3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDetails4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDetails2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBtnPlan6)
                            .addComponent(radioBtnPlan5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetails5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetails6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBtnYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnNo)
                                .addGap(84, 84, 84)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel18)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnPlan1)
                    .addComponent(lblPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnPlan2)
                    .addComponent(lblPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnPlan3)
                    .addComponent(lblPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnPlan4)
                    .addComponent(lblPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnPlan5)
                    .addComponent(lblPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnPlan6)
                    .addComponent(lblPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetails6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18)
                    .addComponent(radioBtnYes)
                    .addComponent(radioBtnNo))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
        
    public void populateMembershipData(){
        this.membershipList = accounting.getMembershipDirectory().getMembershipList();
        for(int i = 0; i < membershipList.size(); i++){
            Membership membership = membershipList.get(i);
            int price = 0;
            switch(i){
                case 0:
                    if(userAccount.getCustomer().getMembership().getName().equals(membership.getName()))
                        radioBtnPlan1.setSelected(true);
                    radioBtnPlan1.setText(membership.getName());
                    radioBtnPlan1.setActionCommand(membership.getName());
                    price = Math.round(membership.getPrice() * membership.getCurrencyMultiplier());
                    lblPrice1.setText(membership.getCurrency()+" "+String.valueOf(price));
                    break;
                case 1:
                    if(userAccount.getCustomer().getMembership().getName().equals(membership.getName()))
                        radioBtnPlan2.setSelected(true);
                    radioBtnPlan2.setText(membership.getName());
                    radioBtnPlan2.setActionCommand(membership.getName());
                    price = Math.round(membership.getPrice() * membership.getCurrencyMultiplier());
                    lblPrice2.setText(membership.getCurrency()+" "+String.valueOf(price));
                    break;
                case 2:
                    if(userAccount.getCustomer().getMembership().getName().equals(membership.getName()))
                        radioBtnPlan3.setSelected(true);
                    radioBtnPlan3.setText(membership.getName());
                    radioBtnPlan3.setActionCommand(membership.getName());
                    price = Math.round(membership.getPrice() * membership.getCurrencyMultiplier());
                    lblPrice3.setText(membership.getCurrency()+" "+String.valueOf(price));
                    break;
                case 3:
                    if(userAccount.getCustomer().getMembership().getName().equals(membership.getName()))
                        radioBtnPlan4.setSelected(true);
                    radioBtnPlan4.setText(membership.getName());
                    radioBtnPlan4.setActionCommand(membership.getName());
                    price = Math.round(membership.getPrice() * membership.getCurrencyMultiplier());
                    lblPrice4.setText(membership.getCurrency()+" "+String.valueOf(price));
                    break;
                case 4:
                    if(userAccount.getCustomer().getMembership().getName().equals(membership.getName()))
                        radioBtnPlan5.setSelected(true);
                    radioBtnPlan5.setText(membership.getName());
                    radioBtnPlan5.setActionCommand(membership.getName());
                    price = Math.round(membership.getPrice() * membership.getCurrencyMultiplier());
                    lblPrice5.setText(membership.getCurrency()+" "+String.valueOf(price));
                    break;
                case 5:
                    if(userAccount.getCustomer().getMembership().getName().equals(membership.getName()))
                        radioBtnPlan6.setSelected(true);
                    radioBtnPlan6.setText(membership.getName());
                    radioBtnPlan6.setActionCommand(membership.getName());
                    price = Math.round(membership.getPrice() * membership.getCurrencyMultiplier());
                    lblPrice6.setText(membership.getCurrency()+" "+String.valueOf(price));
                    break;
            }
        }
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        JRadioButton selectedPlan = (JRadioButton)buttonGroupMembership.getSelection();
        Membership.membershipType type = getMembershipType(selectedPlan.getText());
        
        MembershipDirectory membershipDirectory = accounting.getMembershipDirectory();
        Membership parentMembership = null;
        for(Membership membership: membershipDirectory.getMembershipList()){
            if(membership.getName().equals(type.toString())){
                parentMembership = membership;
                break;
            }
        }
        
        userAccount.getCustomer().getMembership().setName(type);
        userAccount.getCustomer().getMembership().setPrice(parentMembership.getPrice());
        userAccount.getCustomer().getMembership().setDescription(parentMembership.getDescription());
        userAccount.getCustomer().getMembership().setDurationInDays(parentMembership.getDurationInDays());
        userAccount.getCustomer().getMembership().setHasSpecialServicesAccess(parentMembership.getHasSpecialServicesAccess());

        if(radioBtnYes.isSelected())
            userAccount.getCustomer().getMembership().setHasPersonalTraining(Boolean.TRUE);
        else if(radioBtnNo.isSelected())
            userAccount.getCustomer().getMembership().setHasPersonalTraining(Boolean.FALSE);
        
        JOptionPane.showMessageDialog(null, "Congratulations, your membership is renewed!", "Info", JOptionPane.INFORMATION_MESSAGE);    
    }//GEN-LAST:event_btnRegisterActionPerformed

    private Membership.membershipType getMembershipType(String str){
        Membership.membershipType type = null;
        if(str.equals(Membership.membershipType.Bronze.toString()))
            type = Membership.membershipType.Bronze;
        else if(str.equals(Membership.membershipType.Diamond.toString()))
            type = Membership.membershipType.Diamond;
        else if(str.equals(Membership.membershipType.Gold.toString()))
            type = Membership.membershipType.Gold;
        else if(str.equals(Membership.membershipType.Platinum.toString()))
            type = Membership.membershipType.Platinum;
        else if(str.equals(Membership.membershipType.Silver.toString()))
            type = Membership.membershipType.Silver;
        else if(str.equals(Membership.membershipType.Steel.toString()))
            type = Membership.membershipType.Steel;
        
        return type;
    }
    
    private String getDescriptionFromMembershipList(int index){
        int count = 1;
        for(Membership membership: membershipList){
            if(count == index){
                return membership.getDescription();
            }
            count++;
        }
        return null;
    }
    
    private void btnDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetails1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, getDescriptionFromMembershipList(1), "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDetails1ActionPerformed

    private void btnDetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetails2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, getDescriptionFromMembershipList(2), "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDetails2ActionPerformed

    private void btnDetails3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetails3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, getDescriptionFromMembershipList(3), "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDetails3ActionPerformed

    private void btnDetails4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetails4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, getDescriptionFromMembershipList(4), "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDetails4ActionPerformed

    private void btnDetails5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetails5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, getDescriptionFromMembershipList(5), "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDetails5ActionPerformed

    private void btnDetails6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetails6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, getDescriptionFromMembershipList(6), "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDetails6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetails1;
    private javax.swing.JButton btnDetails2;
    private javax.swing.JButton btnDetails3;
    private javax.swing.JButton btnDetails4;
    private javax.swing.JButton btnDetails5;
    private javax.swing.JButton btnDetails6;
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroupHasPersonalTraining;
    private javax.swing.ButtonGroup buttonGroupMembership;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblPrice2;
    private javax.swing.JLabel lblPrice3;
    private javax.swing.JLabel lblPrice4;
    private javax.swing.JLabel lblPrice5;
    private javax.swing.JLabel lblPrice6;
    private javax.swing.JRadioButton radioBtnNo;
    private javax.swing.JRadioButton radioBtnPlan1;
    private javax.swing.JRadioButton radioBtnPlan2;
    private javax.swing.JRadioButton radioBtnPlan3;
    private javax.swing.JRadioButton radioBtnPlan4;
    private javax.swing.JRadioButton radioBtnPlan5;
    private javax.swing.JRadioButton radioBtnPlan6;
    private javax.swing.JRadioButton radioBtnYes;
    // End of variables declaration//GEN-END:variables
}
